blank_issues_enabled: false
contact_links:
  - name: 🚨 Bug report | Bug 提交
    url: https://github.com/anjoy8/Jom.Blog/issues/new
    about: |
      Please report bugs here.
      请在此提交 Bug。
  - name: 🙋 Feature request | 新功能提案
    url: https://github.com/anjoy8/Jom.Blog/issues/new
    about: |
      Please request features here.
      请在此提交新功能提案。
  - name: 🤔 Consulting from the Jom.Blog team | 咨询 作者
    url: https://github.com/anjoy8/Jom.Blog/issues/new
    about: |
      Get technical support, project audits, app deployments, and custom development from the core Jom.Blog team.
      咨询核心 Jom.Blog 团队以获得技术支持，项目审核，应用程序部署以及自定义开发等方面上的帮助。
  - name: ❗️ All other issues | 其他问题
    url: https://github.com/anjoy8/Jom.Blog/issues/new
    about: |
      Please create all other issues here.
      请在此创建其他类型问题。